on:
  push:
    branch:
      - master


name: PHP Linting

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Run phplint
        - uses: michaelw90/PHP-Lint@master
